"""
Newsletter Builder
===================
Builds responsive HTML structure using MSO Ghost Tables.
Images scale dynamically on mobile but remain perfectly contained in Desktop Outlook.
"""

def build_email_html(articles: list[dict], assets: dict) -> str:
    # Build index map: url → CID index (1-based)
    idx_map = {a["url"]: i for i, a in enumerate(articles, 1)}

    # Group by category preserving order
    grouped: dict[str, list[dict]] = {}
    for art in articles:
        grouped.setdefault(art.get("category", "BIGTECH"), []).append(art)

    sections_html = ""
    for cat, arts in grouped.items():
        # Inject the category badge image (1160px Ghost Table)
        badge_cid = f"badge_{cat}"
        sections_html += f"""
        <div style="text-align:center; padding-top:15px;">
          <img src="cid:{badge_cid}" width="1160" style="width: 100%; max-width: 1160px; height: auto; border: none; display: block; margin: 0 auto;">
        </div>
        """
        
        # Inject the individual article cards (826px Ghost Table)
        for a in arts:
            idx = idx_map[a["url"]]
            cid = f"card_{idx:03d}"
            url = a.get("url", "#")
            sections_html += f"""
            <div style="text-align:center; padding-top:10px;">
              <a href="{url}">
                <img src="cid:{cid}" width="826" style="width: 100%; max-width: 826px; height: auto; border: none; display: block; margin: 0 auto;">
              </a>
            </div>
            """

    return f"""<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40">
<head>
  <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=us-ascii">
  <style>
    p.MsoNormal {{margin:0in; font-size:12.0pt; font-family:"Aptos",sans-serif;}}
  </style>
</head>
<body lang=EN-US style="word-wrap:break-word; margin:0; padding:0;">
  <center style="width: 100%;">
    
    <div style="text-align:center;">
      <img src="cid:main_header_img" width="1160" style="width: 100%; max-width: 1160px; height: auto; border: none; display: block; margin: 0 auto;">
    </div>
    <div style="text-align:center;">
      <img src="cid:date_header_img" width="1160" style="width: 100%; max-width: 1160px; height: auto; border: none; display: block; margin: 0 auto;">
    </div>
    {sections_html}

    <p class=MsoNormal align=center style="text-align:center; padding-top:40px; padding-bottom:20px; font-size:10.0pt; color:#666666;">
      this is autogenerated email don't reply message
    </p>

  </center>
</body>
</html>"""


def build_plain_text(articles: list[dict]) -> str:
    lines = ["DAILY TECH NEWS", "=" * 40, ""]
    for i, art in enumerate(articles, 1):
        lines.append(f"{i}. {art.get('title', '')}")
        lines.append(f"   {art.get('url','')}")
        lines.append("")
    lines.append("this is autogenerated email don't reply message")
    return "\n".join(lines)